"""Report and recommendation models.

Defines the output structures generated by the LLM synthesizer:
individual stock recommendations and the complete daily briefing.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field

from src.models.market import SignalStrength


class Recommendation(BaseModel):
    """An actionable recommendation for a single stock."""

    ticker: str
    signal: SignalStrength
    rationale: str = Field(..., description="Why this signal was generated")
    key_levels: dict[str, float] = Field(
        default_factory=dict,
        description="Key price levels (e.g. support, resistance, stop_loss)",
    )
    confidence: float = Field(0.5, ge=0, le=1, description="Model confidence 0-1")


class AlertLevel(str, Enum):
    """Urgency level for alerts."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class Alert(BaseModel):
    """A specific alert or notable event."""

    ticker: str
    level: AlertLevel = AlertLevel.INFO
    title: str
    detail: str


class PortfolioSnapshot(BaseModel):
    """Point-in-time portfolio valuation."""

    total_value: float = Field(0.0, description="Current market value of all holdings")
    total_cost: float = Field(0.0, description="Total cost basis")
    day_change: float = Field(0.0, description="Day's P&L in USD")
    day_change_percent: float = Field(0.0, description="Day's P&L as percentage")
    total_gain: float = Field(0.0, description="Total unrealized P&L in USD")
    total_gain_percent: float = Field(0.0, description="Total unrealized P&L as percentage")


class DailyBriefing(BaseModel):
    """The complete daily report produced by the agent."""

    run_id: str
    run_type: str = Field(..., description="morning or evening")
    generated_at: datetime = Field(default_factory=datetime.utcnow)

    # Market context
    market_overview: str = Field("", description="LLM-generated market summary")

    # Portfolio
    portfolio_snapshot: PortfolioSnapshot = Field(default_factory=PortfolioSnapshot)

    # Per-stock details
    stock_table: list[dict] = Field(
        default_factory=list,
        description="Per-stock row: ticker, price, change, P&L, signal",
    )

    # Alerts (earnings, RSI extremes, big movers, etc.)
    alerts: list[Alert] = Field(default_factory=list)

    # Recommendations
    recommendations: list[Recommendation] = Field(default_factory=list)

    # News digest
    news_digest: str = Field("", description="LLM-summarized news highlights")

    # Full narrative (the main body of the email)
    narrative: str = Field("", description="Full LLM-generated briefing text")
